glue_astronomy/spectral_coordinates.py, glue_astronomy/translators/ccddata.py, glue_astronomy/translators/spectral_cube.py, glue_astronomy/translators/spectrum1d.py, glue_astronomy/translators/tests/test_ccddata.py, glue_astronomy/translators/tests/test_spectral_cube.py, glue_astronomy/translators/tests/test_spectrum1d.py
This fixes the use of the glue.core.coordinates API to be APE-14 compliant as required by recent versions of glue-core.
=> Fix compatibility with latest glue.core.coordinates API

glue_astronomy/translators/ccddata.py, glue_astronomy/translators/spectral_cube.py, glue_astronomy/translators/spectrum1d.py, glue_astronomy/translators/tests/test_ccddata.py, glue_astronomy/translators/tests/test_spectrum1d.py
Glue defines a "mask" as a boolean array where `True` denotes valid data, whereas specutils expects the opposite (`True` in a mask means the data there is masked out/invalid). This PR flips the mask array in the output of the relevant data translators to match what specutils expects, fixing errors that I was getting in multiple plugins of [Jdaviz](https://github.com/spacetelescope/jdaviz/) due to the masks.
=> Flip output masks to match specutils formalism

glue_astronomy/translators/spectrum1d.py, glue_astronomy/translators/tests/test_spectrum1d.py
This updates the `Spectrum1D` translator to also include the uncertainties and mask on the spectrum instance as glue components.
=> Use uncertainties and mask from `Spectrum1D`

glue_astronomy/translators/ccddata.py, glue_astronomy/translators/spectral_cube.py, glue_astronomy/translators/spectrum1d.py, glue_astronomy/translators/tests/test_spectrum1d.py
=> Store correct units for uncertainty in Glue data object

glue_astronomy/translators/spectral_cube.py, glue_astronomy/translators/tests/test_spectral_cube.py
Meta data included in the `SpectralCube` translation to a Glue `Data` object is stored, but not added when the data is translated back to a `SpectralCube`. This PR includes the meta data information on translation.
=> Add meta data on spectral cube translation

glue_astronomy/translators/regions.py
Potentially fixes #31 
I'm not sure if anything else needs to be done here to implement elliptical ROI in glue-astronomy, and by extension jdaviz. Testing on my machine does not look different but I'm not sure if further changes need to be made in glue-jupyter or jdaviz.
=> Add support for elliptical ROI

azure-pipelines.yml
This is an attempt to fix the liunux CI that's been broken for a while.
I think this might be trivial.  libgfortran3 is pretty old and hence is gone from some more recent linux distros.  I'm not certain what ubuntu version the CI is currently running on, but seems like a reasonable wild guess...
=> libgfortran3 -> libgfortran5

glue_astronomy/translators/spectrum1d.py
This is my attempt to fix spacetelescope/jdaviz#821 . With this patch, the code snippet posted in spacetelescope/jdaviz#821 went from traceback to this:
```python
>>> spec = data.get_object(cls=Spectrum1D) 
<Spectrum1D(flux=<Quantity [1., 1., 1.]>, spectral_axis=<SpectralAxis
(observer to target:
radial_velocity=0.0 km / s
redshift=0.0)
[1., 2., 3.] Hz>)>
```
I don't grok why the default was changed in #36 , so @rosteen or @astrofrog can comment.
=> Change Spectrum1DHandler default stat back to mean

glue_astronomy/translators/spectrum1d.py, glue_astronomy/translators/tests/test_spectrum1d.py
This adds a way to translate Spectrum1D objects with 1D spectral WCS and 2D datasets to glue objects and back, and is needed for https://github.com/spacetelescope/jdaviz/pull/733. In future we should just support ND datasets with 1D WCS but the code for that will be a bit more complex and it would be easier to just wait for a release of NDCube so that we can use the compound WCS class from there. For now this PR makes it possible to support 2D spectra.
This also removes the use of SpectralCoordinate in ``to_data`` as glue and Spectrum1D now both support GWCS.
=> Support Spectrum1D objects with 2D data and 1D WCS

glue_astronomy/translators/spectrum1d.py
This PR fixes regression in Cubeviz parser behavior introduced in spacetelescope/jdaviz#547 , particularly getting rid of the assumption that "uncertainty" is always available when "flux" is available, which is not always true.
~Also refactor the internal logic a little.~
Fixes spacetelescope/jdaviz#967
=> Fix attribute handling for Jdaviz/Cubeviz parser

glue_astronomy/translators/ccddata.py
Return NDData for GWCS instead of crashing in CCDData.
This works around astropy/astropy#11727 and is a hacky version of #38.
cc @rosteen
=> Return NDData for GWCS

.gitignore, .readthedocs.yml, MANIFEST.in, README.rst, azure-pipelines.yml, docs/conf.py, glue_astronomy/__init__.py, glue_astronomy/io/spectral_cube/tests/test_spectral_cube.py, glue_astronomy/translators/tests/test_spectrum1d.py, pyproject.toml, setup.cfg, setup.py, tox.ini
I could not run tests locally, then I realized the packaging state of this package is way outdated. This pull request is to:
* Modernize packaging.
* Turn unhandled warnings into exceptions.
* Update test matrix.
* Fix test package data.
* Handle test warnings.
Out of scope:
* #65
=> MNT: Modernize packaging, etc

azure-pipelines.yml, glue_astronomy/io/spectral_cube/tests/test_spectral_cube.py, setup.cfg, tox.ini
... since spectral-cube now depends on casa-formats-io by default
Fixes https://github.com/glue-viz/glue-astronomy/pull/65
=> No longer test against casatools and casatasks

.github/workflows/main.yml
Follow-up to #69 adding a `publish_pure_python` job.
=> Add publish job to workflow

CHANGES.rst, glue_astronomy/translators/regions.py, glue_astronomy/translators/tests/test_regions.py
As of 1.5.0 `glue` supports rotation angles in ROIs, breaking the `NotImplementedError` test.
This is updating the test and exporting the rotation angle `theta`, if set, to Astropy `regions` created from an ROI.
Also removed the `pytest.raises` for the no longer failing logical operations in `test_invalid_combos`.
=> Export `roi.theta` in 'astropy-regions' translator and run passing tests

CHANGES.rst, docs/translators.rst, glue_astronomy/translators/__init__.py, glue_astronomy/translators/tests/test_trace.py, glue_astronomy/translators/trace.py, setup.cfg
This PR implements a new translator for [specreduce Trace objects](https://specreduce.readthedocs.io/en/latest/#module-specreduce.tracing).  In doing so, it adds specreduce as a dependency.  In order to round-trip and retrieve the same underyling Trace object (instead of always having to export to an `ArrayTrace`), this currently saves a copy of the input Trace object in the `meta` of the glue `Data` object.  If this is not preferred, we could create an `ArrayTrace` from the glue `Data` object, but we'll likely still need to attach an instance or reference to the input data.
=> translator for specreduce Trace objects

glue_astronomy/translators/spectrum1d.py
Without this patch, loading an uncalibrated 2D spectrum without wavelength axis will crash.
=> Return empty string instead of crashing when UCD_TO_SPECTRAL_NAME lookup failed

CHANGES.rst, glue_astronomy/translators/spectrum1d.py, glue_astronomy/translators/tests/test_spectrum1d.py
Parse units for Spectrum1D for all occasions. We need this so flux unit is shown correctly in Jdaviz for 2D and 3D spectra. Fix https://github.com/spacetelescope/jdaviz/issues/1625
We also need this for https://github.com/spacetelescope/jdaviz/pull/1608
Also simplify Spectrum1D parser logic.
cc @dhomeier @astrofrog 
[🐱](https://jira.stsci.edu/browse/JDAT-2723)
=> BUG: Parse units for Spectrum1D for all occasions

CHANGES.rst, glue_astronomy/translators/spectral_cube.py
The `SpectralCube` handlers didn't work for any but the basic single-beam SpectralCube objects.  This adds support for the other types.
I haven't tested this extensively yet, but I think the ideas are sound - as long as the metadata is appropriately preserved.
Problem: `beams` needs to be subsetted along with the data.  How can we handle that?
=> add more spectral-cube class translators

glue_astronomy/spectral_coordinates.py, glue_astronomy/tests/test_spectral_coordinates.py, glue_astronomy/translators/tests/test_spectrum1d.py
The pixel <-> world methods should return single scalars/arrays not tuples in order to be APE-14-compliant.
=> Fixed return type and shape for pixel <-> world conversions in SpectralCoordinates

.github/workflows/main.yml, setup.cfg, tox.ini
glue-astronomy is now only compatible with glue-core 1.6.1 or later. Also see:
* https://github.com/spacetelescope/jdaviz/issues/1974
This is because https://github.com/glue-viz/glue-astronomy/pull/82 was released as part of glue-astronomy 0.6.0 and it requires https://github.com/glue-viz/glue/pull/2345 that was released as part of glue-core 1.6.1
cc @astrofrog and @dhomeier
=> Require glue-core >= 1.6.1, dropped Python 3.7 support

glue_astronomy/translators/nddata.py, glue_astronomy/translators/spectral_cube.py, glue_astronomy/translators/spectrum1d.py
To fix support for glue-viz/glue#2296.
Other uses of `component.units` in the translators (`NDDataArray`, `StdDevUncertainty`) already accept `unit=None`, so it seems most sensible to switch to the `u.Quantity()` format here.
Added glue to devdeps to test this (might be a good idea in general?)
=> Accept `component.units=None` in translators input

glue_astronomy/translators/nddata.py, glue_astronomy/translators/tests/test_nddata.py
In #81, I added translators for objects in `astropy.nddata`. In this PR, I add support for extracting uncertainties from glue `Data` objects and translating them into the `uncertainty` attr in `NDDataArray` objects. This was missing in the previous PR, but should have been there.
=> Adding support for uncertainty extraction to NDDataArray

glue_astronomy/translators/regions.py
Fixing a regression following glue-viz/glue#2391, which deprecated `get_center` and `set_center` in favour of using `center` and `move_to` consistently for all ROIs.
=> Use `CircularROI.center` to avoid deprecation warnings with glue_core >= 1.10

glue_astronomy/translators/regions.py, glue_astronomy/translators/tests/test_regions.py
Support new CircularAnnulusROI from glue-viz/glue#2403 (not yet merged when this PR is opened, so dev tests might fail, so we need to rerun that when it is merged upstream) by building on https://github.com/glue-viz/glue-astronomy/pull/90 .
Motivation: Instead of exposting the outer and inner circles separately in Jdaviz, we can now expose the proper annulus parameters by using this new ROI.
[🐱](https://jira.stsci.edu/browse/JDAT-3395)
=> FEAT: Support new CircularAnnulusROI

glue_astronomy/translators/regions.py, glue_astronomy/translators/tests/test_regions.py
There is a need for Jdaviz to be able to call the translator code directly and have option to get back sky regions. The first part is useful for spatial region translations where we pass in the subset state directly internally and there is really no need to access `subset.data`. This blocks:
* https://github.com/spacetelescope/jdaviz/pull/2240
* spacetelescope/jdaviz#2250
Fix #89 
cc @dhomeier or @astrofrog
=> FEAT: Support sky regions and allow direct call to translator function

.github/workflows/main.yml
Testing whether this solves the issue of GitHub actions not running
=> Don't set PLAT in GitHub Actions config

glue_astronomy/translators/regions.py, glue_astronomy/translators/tests/test_regions.py
Closing https://github.com/glue-viz/glue-astronomy/pull/96/files as the workaround in there can go directly in Jdaviz, but keeping changes to docstring/tests for the `roi_subset_state_to_region` function. Not including a change log entry for this.
=> Document and check WCS usage for `to_sky` option in subset-to-region translator; add tests

.github/workflows/main.yml, tox.ini
Astropy 6.0dev has removed a number of deprecated functions, breaking CI through spectral_cube, with a fix merged, but not released. Adding it to the git-installs for `dev` at least temporarily, and also adding glue-qt to keep sync'ed with glue-core. Finally throwing in a py312 test job.
=> Add spectral_cube, glue-qt to devdeps; test py312

.github/workflows/main.yml, glue_astronomy/translators/tests/test_trace.py
Function name has been changed in astropy/specreduce#165. This has also introduced a new, default-True option `add_noise`, which requires `photutils`. I suppose it is not of interest for the functionality tested here, or should I add `photutils` to test-deps and use the default?
=> Update test_trace to specreduce 1.4 interface

glue_astronomy/translators/nddata.py, glue_astronomy/translators/tests/test_nddata.py
The NDData translator checks that the `Data.coords` is either a WCS object, a glue `Coordinates` object, or None. Other Coordinates types are not allowed in the current logic. I'm trying to work with a case where the coordinate attribute that's an `IdentityCoordinate`, but that's disallowed. 
This PR simply allows `coords` attributes that are subclasses of Coordinates.
=> Loosen check on coordinate class for NDData translator to accept subclasses

docs/translators.rst, glue_astronomy/translators/nddata.py, glue_astronomy/translators/spectrum1d.py, glue_astronomy/translators/tests/test_spectrum1d.py, glue_astronomy/translators/tests/test_trace.py, setup.cfg, tox.ini
Adding better handling of GWCS in the Spectrum1D handler. Opening as draft since this may need a couple other changes/additions, and because it shouldn't be merged until specutils 2.0 is ready for release. I'll also add some test coverage for the new code.
=> Handle GWCS for specutils 2.0 compatibility

.pre-commit-config.yaml, .ruff.toml, CHANGES.md, glue_astronomy/io/spectral_cube/spectral_cube.py, glue_astronomy/spectral_coordinates.py, glue_astronomy/translators/regions.py, glue_astronomy/translators/spectral_cube.py, glue_astronomy/translators/spectrum1d.py, pyproject.toml, tox.ini
Adding basic configuration for ruff codestyle, but not format checks along the lines of glue-viz/glue-qt#31 – see also there for documentation:
1. temporary exceptions listed in `.ruff.toml`
2. (more) permanent exceptions in `pyproject.toml`
3. some straightforward fixes in the files in the second commit
=> Add pre-commit and test configuration for ruff codestyle checks
